/*
 * asmdb.c
 * Static reference data for the nStudio editor:
 *   - ARM mnemonic catalog (names, signatures, descriptions, CPSR notes)
 *   - Ndless syscall catalog
 *   - cheat-sheet lookup helpers
 */

#include <stddef.h>
#include <string.h>

#include "asmdb.h"
#include "optab.h"
#include "util.h"

/* ================================================================
 * ARM Mnemonic database
 * Each entry carries: lowercase name, argument signature, description.
 * ================================================================ */
static const MnemInfo db_move[] = {
    {"mov", "Rd, Op2", "Move: Rd = Op2.",
     "With 'S': updates N,Z, C from shifter, V unchanged."},
    {"mvn", "Rd, Op2", "Move NOT: Rd = ~Op2.",
     "With 'S': updates N,Z, C from shifter, V unchanged."},
    {"mrs", "Rd, cpsr|spsr", "Move PSR to Register: Rd = CPSR or SPSR.",
     "No flags modified."},
    {"msr", "cpsr|spsr_<flg>, Op",
     "Move Register to PSR: CPSR/SPSR = Rm or #imm.",
     "Updates CPSR flags directly if fields include 'f'."},
};
static const MnemInfo db_arith[] = {
    {"add", "Rd, Rn, Op2", "Add: Rd = Rn + Op2.", "With 'S': updates N,Z,C,V."},
    {"adc", "Rd, Rn, Op2", "Add with Carry: Rd = Rn + Op2 + C.",
     "With 'S': updates N,Z,C,V."},
    {"sub", "Rd, Rn, Op2", "Subtract: Rd = Rn - Op2.",
     "With 'S': updates N,Z,C,V."},
    {"sbc", "Rd, Rn, Op2", "Subtract with Carry: Rd = Rn - Op2 - NOT(C).",
     "With 'S': updates N,Z,C,V."},
    {"rsb", "Rd, Rn, Op2", "Reverse Subtract: Rd = Op2 - Rn.",
     "With 'S': updates N,Z,C,V."},
    {"rsc", "Rd, Rn, Op2",
     "Reverse Subtract with Carry: Rd = Op2 - Rn - NOT(C).",
     "With 'S': updates N,Z,C,V."},
    {"mul", "Rd, Rm, Rs", "Multiply (32-bit): Rd = Rm * Rs.",
     "With 'S': updates N,Z. C,V unpredictable."},
    {"mla", "Rd, Rm, Rs, Rn", "Multiply Accumulate: Rd = (Rm * Rs) + Rn.",
     "With 'S': updates N,Z. C,V unpredictable."},
    {"umull", "RdLo, RdHi, Rm, Rs",
     "Unsigned Long Multiply: {RdHi,RdLo} = Rm * Rs.",
     "With 'S': updates N,Z. C,V unpredictable."},
    {"umlal", "RdLo, RdHi, Rm, Rs",
     "Unsigned Long Multiply Accum: {RdHi,RdLo} += Rm * Rs.",
     "With 'S': updates N,Z. C,V unpredictable."},
    {"smull", "RdLo, RdHi, Rm, Rs",
     "Signed Long Multiply: {RdHi,RdLo} = Rm * Rs.",
     "With 'S': updates N,Z. C,V unpredictable."},
    {"smlal", "RdLo, RdHi, Rm, Rs",
     "Signed Long Multiply Accum: {RdHi,RdLo} += Rm * Rs.",
     "With 'S': updates N,Z. C,V unpredictable."},
    {"clz", "Rd, Rm", "Count Leading Zeros: Rd = number of 0s at MSB of Rm.",
     "No flags modified."},
};
static const MnemInfo db_logic[] = {
    {"and", "Rd, Rn, Op2", "Bitwise AND: Rd = Rn & Op2.",
     "With 'S': updates N,Z, C from shifter, V unchanged."},
    {"orr", "Rd, Rn, Op2", "Bitwise OR: Rd = Rn | Op2.",
     "With 'S': updates N,Z, C from shifter, V unchanged."},
    {"eor", "Rd, Rn, Op2", "Bitwise Exclusive OR: Rd = Rn ^ Op2.",
     "With 'S': updates N,Z, C from shifter, V unchanged."},
    {"bic", "Rd, Rn, Op2", "Bit Clear: Rd = Rn & ~Op2.",
     "With 'S': updates N,Z, C from shifter, V unchanged."},
};
static const MnemInfo db_cmp[] = {
    {"cmp", "Rn, Op2", "Compare: computes Rn - Op2.",
     "Always updates N,Z,C,V."},
    {"cmn", "Rn, Op2", "Compare Negative: computes Rn + Op2.",
     "Always updates N,Z,C,V."},
    {"tst", "Rn, Op2", "Test: computes Rn & Op2.",
     "Always updates N,Z, C from shifter, V unchanged."},
    {"teq", "Rn, Op2", "Test Equivalence: computes Rn ^ Op2.",
     "Always updates N,Z, C from shifter, V unchanged."},
};
static const MnemInfo db_branch[] = {
    {"b", "label", "Branch: PC = label.", "No flags modified."},
    {"bl", "label", "Branch with Link: LR = PC + 4, PC = label.",
     "No flags modified."},
    {"bx", "Rm", "Branch and Exchange: PC = Rm, switch to Thumb if Rm[0]=1.",
     "Updates CPSR T-bit if switching modes."},
};
static const MnemInfo db_ldr[] = {
    {"ldr", "Rd, [Rn, Op]", "Load Word: Rd = [mem32].", "No flags modified."},
    {"ldrb", "Rd, [Rn, Op]", "Load Byte: Rd = ZeroExt([mem8]).",
     "No flags modified."},
    {"ldrh", "Rd, [Rn, Op]", "Load Halfword: Rd = ZeroExt([mem16]).",
     "No flags modified."},
    {"ldrsb", "Rd, [Rn, Op]", "Load Signed Byte: Rd = SignExt([mem8]).",
     "No flags modified."},
    {"ldrsh", "Rd, [Rn, Op]", "Load Signed Halfword: Rd = SignExt([mem16]).",
     "No flags modified."},
    {"ldrt", "Rd, [Rn]", "Load Word Unprivileged: Rd = [mem32].",
     "No flags modified."},
    {"ldrbt", "Rd, [Rn]", "Load Byte Unprivileged: Rd = ZeroExt([mem8]).",
     "No flags modified."},
};
static const MnemInfo db_str[] = {
    {"str", "Rd, [Rn, Op]", "Store Word: [mem32] = Rd.", "No flags modified."},
    {"strb", "Rd, [Rn, Op]", "Store Byte: [mem8] = Rd[7:0].",
     "No flags modified."},
    {"strh", "Rd, [Rn, Op]", "Store Halfword: [mem16] = Rd[15:0].",
     "No flags modified."},
    {"strt", "Rd, [Rn]", "Store Word Unprivileged: [mem32] = Rd.",
     "No flags modified."},
    {"strbt", "Rd, [Rn]", "Store Byte Unprivileged: [mem8] = Rd[7:0].",
     "No flags modified."},
};
static const MnemInfo db_ldm[] = {
    {"ldm", "Rn{!}, reglist",
     "Load Multiple: load registers from [Rn] (default IA).",
     "No flags modified (unless PC loaded with ^: restores CPSR)."},
    {"ldmia", "Rn{!}, reglist", "Load Multiple, Increment After (same as LDM).",
     "No flags modified."},
    {"ldmib", "Rn{!}, reglist", "Load Multiple, Increment Before.",
     "No flags modified."},
    {"ldmda", "Rn{!}, reglist", "Load Multiple, Decrement After.",
     "No flags modified."},
    {"ldmdb", "Rn{!}, reglist", "Load Multiple, Decrement Before.",
     "No flags modified."},
    {"ldmfd", "Rn{!}, reglist",
     "Load Multiple, Full Descending (alias for LDMIA).", "No flags modified."},
    {"ldmed", "Rn{!}, reglist",
     "Load Multiple, Empty Descending (alias for LDMIB).",
     "No flags modified."},
    {"ldmfa", "Rn{!}, reglist",
     "Load Multiple, Full Ascending (alias for LDMDA).", "No flags modified."},
    {"ldmea", "Rn{!}, reglist",
     "Load Multiple, Empty Ascending (alias for LDMDB).", "No flags modified."},
};
static const MnemInfo db_stm[] = {
    {"stm", "Rn{!}, reglist",
     "Store Multiple: store registers to [Rn] (default IA).",
     "No flags modified."},
    {"stmia", "Rn{!}, reglist",
     "Store Multiple, Increment After (same as STM).", "No flags modified."},
    {"stmib", "Rn{!}, reglist", "Store Multiple, Increment Before.",
     "No flags modified."},
    {"stmda", "Rn{!}, reglist", "Store Multiple, Decrement After.",
     "No flags modified."},
    {"stmdb", "Rn{!}, reglist", "Store Multiple, Decrement Before.",
     "No flags modified."},
    {"stmfd", "Rn{!}, reglist",
     "Store Multiple, Full Descending (alias for STMDB).",
     "No flags modified."},
    {"stmed", "Rn{!}, reglist",
     "Store Multiple, Empty Descending (alias for STMDA).",
     "No flags modified."},
    {"stmfa", "Rn{!}, reglist",
     "Store Multiple, Full Ascending (alias for STMIB).", "No flags modified."},
    {"stmea", "Rn{!}, reglist",
     "Store Multiple, Empty Ascending (alias for STMIA).",
     "No flags modified."},
};
static const MnemInfo db_cop[] = {
    {"mcr", "cp, op, Rd, CRn, CRm, op2",
     "Move to Coprocessor from ARM Register.", "No ARM flags modified."},
    {"mrc", "cp, op, Rd, CRn, CRm, op2",
     "Move to ARM Register from Coprocessor.",
     "If Rd=R15, updates ARM N,Z,C,V flags."},
    {"swp", "Rd, Rm, [Rn]", "Swap Word: atomic memory read and write.",
     "No flags modified."},
    {"swpb", "Rd, Rm, [Rn]", "Swap Byte: atomic memory read and write.",
     "No flags modified."},
};
static const MnemInfo db_misc[] = {
    {"swi", "#imm", "Software Interrupt (legacy): triggers SVC exception.",
     "No flags modified."},
    {"svc", "#imm", "Supervisor Call: triggers SVC exception.",
     "No flags modified."},
};
static const MnemInfo db_shifts[] = {
    {"lsl", "Rm, #n|Rs", "Logical Shift Left: Rd = Rm << Op.",
     "Used as Op2: updates C. With 'S': updates N,Z,C."},
    {"asl", "Rm, #n|Rs", "Arithmetic Shift Left: alias of LSL.",
     "Used as Op2: updates C. With 'S': updates N,Z,C."},
    {"lsr", "Rm, #n|Rs", "Logical Shift Right: Rd = Rm >> Op.",
     "Used as Op2: updates C. With 'S': updates N,Z,C."},
    {"asr", "Rm, #n|Rs",
     "Arithmetic Shift Right: Rd = Rm >> Op (sign-extended).",
     "Used as Op2: updates C. With 'S': updates N,Z,C."},
    {"ror", "Rm, #n|Rs", "Rotate Right: Rd = Rm rotated by Op.",
     "Used as Op2: updates C. With 'S': updates N,Z,C."},
    {"rrx", "Rm", "Rotate Right Extended: Rd = (C << 31) | (Rm >> 1).",
     "Used as Op2: updates C. With 'S': updates N,Z,C."},
};

/* Pseudo-instructions provided by the nasm assembler */
static const MnemInfo db_pseudo[] = {
    {"adr", "Rd, label",
     "Load PC-relative address of a nearby label using ADD/SUB.",
     "No flags modified."},
    {"push", "{reglist}",
     "Push registers: alias for STMFD SP!,{list}. A single-register list "
     "uses the STR encoding.",
     "No flags modified."},
    {"pop", "{reglist}",
     "Pop registers: alias for LDMFD SP!,{list}. A single-register list "
     "uses the LDR encoding.",
     "No flags modified (unless PC is loaded)."},
    {"nop", "", "No operation: assembles to MOV R0,R0.",
     "No flags modified."},
    {"ldr", "Rd, =value",
     "Load a 32-bit constant: MOV/MVN when encodable, otherwise loaded "
     "PC-relative from a literal pool (emitted at LTORG or at the end of "
     "the program). value may be a named constant or label expression.",
     "No flags modified."},
};

/* Assembler directives supported by nasm */
static const MnemInfo db_directives[] = {
    {"align", "{n}", "Align the next output to an n-byte boundary.", ""},
    {"dcb", "expr|\"str\", ...", "Define bytes or string data in memory.",
     ""},
    {"dcw", "expr, ...", "Define 16-bit halfwords (DCWU: unaligned).", ""},
    {"dcd", "expr, ...", "Define 32-bit words (DCDU: unaligned).", ""},
    {"equ", "value",
     "Define a named constant: name EQU value, with the name in column 0 "
     "like any label. Usable wherever an immediate is allowed.",
     ""},
    {"ltorg", "", "Emit the pending LDR = literal pool here.", ""},
    {"include", "\"file\"", "Assemble another source file here (alias: GET).",
     ""},
    {"incbin", "\"file\"", "Include a binary file verbatim.", ""},
};

CatalogCat g_cats[NCATS];
static int g_cats_init = 0;

#define ASIZE(a) ((int)(sizeof(a) / sizeof((a)[0])))

void catalog_init_cats(void) {
  if (g_cats_init)
    return;
  int i = 0;
  g_cats[i++] = (CatalogCat){"Data Transfer", db_move, ASIZE(db_move), 1};
  g_cats[i++] = (CatalogCat){"Arithmetic", db_arith, ASIZE(db_arith), 1};
  g_cats[i++] = (CatalogCat){"Logic", db_logic, ASIZE(db_logic), 1};
  g_cats[i++] = (CatalogCat){"Comparison", db_cmp, ASIZE(db_cmp), 1};
  g_cats[i++] = (CatalogCat){"Branch", db_branch, ASIZE(db_branch), 1};
  g_cats[i++] = (CatalogCat){"Load (single)", db_ldr, ASIZE(db_ldr), 1};
  g_cats[i++] = (CatalogCat){"Store (single)", db_str, ASIZE(db_str), 1};
  g_cats[i++] = (CatalogCat){"Load (multiple)", db_ldm, ASIZE(db_ldm), 0};
  g_cats[i++] = (CatalogCat){"Store (multiple)", db_stm, ASIZE(db_stm), 0};
  g_cats[i++] = (CatalogCat){"Coprocessor", db_cop, ASIZE(db_cop), 0};
  g_cats[i++] = (CatalogCat){"Miscellaneous", db_misc, ASIZE(db_misc), 1};
  g_cats[i++] = (CatalogCat){"Pseudo-instructions", db_pseudo,
                             ASIZE(db_pseudo), 1};
  g_cats[i++] = (CatalogCat){"Shift Operators", db_shifts, ASIZE(db_shifts), 1};
  g_cats[i++] = (CatalogCat){"Directives", db_directives,
                             ASIZE(db_directives), 0};
  g_cats_init = 1;
}

/* ================================================================
 * Ndless Syscall Catalog
 * ================================================================ */
/* ================================================================
 * Ndless Syscall Catalog (Complete List)
 * ================================================================ */
const SyscallInfo db_syscalls[] = {
    /* File I/O & Nucleus RTOS */
    {"fopen", 0, "const char *path, const char *mode",
     "Opens a file (Nucleus)."},
    {"fread", 1, "void *ptr, size_t size, size_t count, NUC_FILE *stream",
     "Reads data from a file."},
    {"fwrite", 2, "void *ptr, size_t size, size_t count, NUC_FILE *stream",
     "Writes data to a file."},
    {"fclose", 3, "NUC_FILE *stream", "Closes an open file."},
    {"fgets", 4, "char *str, int n, NUC_FILE *stream",
     "Reads a string from a file."},
    {"printf", 10, "const char *format, ...", "Prints formatted output."},
    {"sprintf", 11, "char *str, const char *format, ...",
     "Formats and stores characters."},
    {"fprintf", 12, "FILE *stream, const char *format, ...",
     "Prints formatted output to a file."},
    {"TCT_Local_Control_Interrupts", 14, "int mask",
     "Sets the interrupt mask."},
    {"mkdir", 15, "const char *path, mode_t mode", "Creates a directory."},
    {"rmdir", 16, "const char *path", "Removes a directory."},
    {"chdir", 17, "const char *path", "Changes current working directory."},
    {"stat", 18, "const char *path, struct nuc_stat *buf", "Gets file status."},
    {"unlink", 19, "const char *path", "Deletes a file."},
    {"rename", 20, "const char *oldname, const char *newname",
     "Renames a file."},
    {"TCC_Terminate_Task", 21, "NU_TASK *task", "Terminates a Nucleus task."},
    {"puts", 22, "const char *str", "Writes a string to stdout."},
    {"NU_Get_First", 23, "struct dstat *statobj, const char *pattern",
     "Finds first file matching pattern."},
    {"NU_Get_Next", 24, "struct dstat *statobj",
     "Finds next file matching pattern."},
    {"NU_Done", 25, "struct dstat *statobj", "Frees dstat structure elements."},
    {"show_dialog_box2_", 30,
     "int p1, const char *t, const char *m, const char **b",
     "Shows a basic dialog box."},
    {"_vsprintf", 32, "char *str, const char *format, va_list ap",
     "Formatted output to string."},
    {"fseek", 33, "NUC_FILE *stream, long offset, int whence",
     "Sets file position indicator."},
    {"NU_Current_Dir", 34, "const char *drive, char *path",
     "Gets current working directory."},
    {"read_unaligned_longword", 35, "const void *ptr",
     "Reads 32-bit unaligned word."},
    {"read_unaligned_word", 36, "const void *ptr",
     "Reads 16-bit unaligned word."},
    {"fgetc", 52, "FILE *stream", "Gets next character from file."},
    {"NU_Set_Current_Dir", 53, "const char *name",
     "Sets current working directory."},
    {"fputc", 54, "int char, FILE *stream", "Writes character to file."},
    {"freopen", 60, "const char *path, const char *mode, FILE *stream",
     "Reopens a file stream."},
    {"errno_addr", 61, "void", "Returns pointer to errno."},
    {"ungetc", 65, "int char, FILE *stream",
     "Pushes character back to stream."},
    {"fflush", 69, "FILE *stream", "Flushes output buffer."},
    {"remove", 70, "const char *filename", "Deletes a file."},
    {"stdin", 71, "void", "Standard input stream."},
    {"stdout", 72, "void", "Standard output stream."},
    {"stderr", 73, "void", "Standard error stream."},
    {"ferror", 74, "FILE *stream", "Tests error indicator on stream."},
    {"TCC_Current_Task_Pointer", 88, "void",
     "Returns pointer to current Nucleus task."},
    {"ftell", 89, "NUC_FILE *stream", "Returns current file position."},
    {"NU_Open", 90, "char *path, uint32_t flags, uint32_t mode",
     "Opens a Nucleus file descriptor."},
    {"NU_Close", 91, "PCFD fd", "Closes a Nucleus file descriptor."},
    {"NU_Truncate", 92, "PCFD fd, long int size",
     "Truncates a Nucleus file descriptor."},
    {"_show_msgbox_2b", 93,
     "int p1, const char *t, const char *m, const char *b1, ...",
     "Message box with 2 buttons."},
    {"_show_msgbox_3b", 94,
     "int p1, const char *t, const char *m, const char *b1, ...",
     "Message box with 3 buttons."},
    {"opendir", 95, "const char *path", "Opens a directory stream."},
    {"readdir", 96, "NUC_DIR *dirp", "Reads directory entry."},
    {"closedir", 97, "NUC_DIR *dirp", "Closes directory stream."},

    /* Strings, Memory & CTYPE */
    {"malloc", 5, "size_t size", "Allocates memory."},
    {"free", 6, "void *ptr", "Frees memory."},
    {"memset", 7, "void *str, int c, size_t n", "Fills memory."},
    {"memcpy", 8, "void *dest, const void *src, size_t n", "Copies memory."},
    {"memcmp", 9, "const void *str1, const void *str2, size_t n",
     "Compares memory."},
    {"strcmp", 26, "const char *str1, const char *str2", "Compares strings."},
    {"strcpy", 27, "char *dest, const char *src", "Copies string."},
    {"strncat", 28, "char *dest, const char *src, size_t n",
     "Concatenates string (max n)."},
    {"strlen", 29, "const char *str", "Gets string length."},
    {"strrchr", 31, "const char *str, int c", "Finds last occurrence of char."},
    {"strncpy", 37, "char *dest, const char *src, size_t n",
     "Copies string (max n)."},
    {"isalpha", 38, "int c", "Checks if character is alphabetic."},
    {"isascii", 39, "int c", "Checks if character is ASCII."},
    {"isdigit", 40, "int c", "Checks if character is a digit."},
    {"islower", 41, "int c", "Checks if character is lowercase."},
    {"isprint", 42, "int c", "Checks if character is printable."},
    {"isspace", 43, "int c", "Checks if character is whitespace."},
    {"isupper", 44, "int c", "Checks if character is uppercase."},
    {"isxdigit", 45, "int c", "Checks if character is hex digit."},
    {"tolower", 46, "int c", "Converts character to lowercase."},
    {"atoi", 47, "const char *str", "Converts string to integer."},
    {"atof", 48, "const char *str", "Converts string to double."},
    {"calloc", 49, "size_t nitems, size_t size",
     "Allocates zero-initialized memory."},
    {"realloc", 50, "void *ptr, size_t size", "Reallocates memory."},
    {"strpbrk", 51, "const char *str1, const char *str2",
     "Finds first matching character."},
    {"memmove", 55, "void *dest, const void *src, size_t n",
     "Moves memory block securely."},
    {"memrev", 56, "void *str, size_t n", "Reverses a memory block."},
    {"strchr", 57, "const char *str, int c", "Finds first occurrence of char."},
    {"strncmp", 58, "const char *str1, const char *str2, size_t n",
     "Compares strings (max n)."},
    {"toupper", 62, "int c", "Converts character to uppercase."},
    {"strtod", 63, "const char *str, char **endptr",
     "Converts string to double."},
    {"strtol", 64, "const char *str, char **endptr, int base",
     "Converts string to long integer."},
    {"strerror", 66, "int errnum", "Gets string describing error number."},
    {"strcat", 67, "char *dest, const char *src", "Concatenates strings."},
    {"strstr", 68, "const char *haystack, const char *needle",
     "Finds substring."},
    {"strtok", 200, "char *str, const char *delim", "Tokenizes a string."},
    {"rand", 206, "void", "Returns a pseudo-random integer."},
    {"srand", 207, "unsigned int seed", "Seeds the random number generator."},
    {"strtoul", 208, "const char *str, char **endptr, int base",
     "Converts string to unsigned long."},
    {"sscanf", 266, "const char *str, const char *format, ...",
     "Reads formatted input from string."},
    {"snprintf", 332, "char *str, size_t size, const char *format, ...",
     "Safe formatted output to string."},
    {"_vprintf", 333, "const char *format, va_list ap",
     "Formatted output to stdout."},
    {"_vfprintf", 334, "FILE *stream, const char *format, va_list ap",
     "Formatted output to file."},
    {"_vsnprintf", 335,
     "char *str, size_t size, const char *format, va_list ap",
     "Safe formatted output to string."},

    /* Zlib Compression */
    {"adler32", 77, "uLong adler, const Bytef *buf, uInt len",
     "Computes Adler-32 checksum."},
    {"crc32", 78, "uLong crc, const Bytef *buf, uInt len",
     "Computes CRC-32 checksum."},
    {"crc32_combine", 79, "uLong crc1, uLong crc2, z_off_t len2",
     "Combines two CRC-32 checksums."},
    {"zlibVersion", 80, "void", "Returns zlib version string."},
    {"zlibCompileFlags", 81, "void", "Returns zlib compile flags."},
    {"deflateInit2_", 82, "z_streamp strm, int level, int method, ...",
     "Initializes compression."},
    {"deflate", 83, "z_streamp strm, int flush", "Compresses data."},
    {"deflateEnd", 84, "z_streamp strm", "Ends compression."},
    {"inflateInit2_", 85, "z_streamp strm, int windowBits, ...",
     "Initializes decompression."},
    {"inflate", 86, "z_streamp strm, int flush", "Decompresses data."},
    {"inflateEnd", 87, "z_streamp strm", "Ends decompression."},

    /* Hardware, Touchpad & Events */
    {"touchpad_read", 75, "unsigned char p1, unsigned char p2, void *p3",
     "Reads touchpad state."},
    {"touchpad_write", 76, "unsigned char p1, unsigned char p2, void *p3",
     "Writes touchpad state."},
    {"keypad_type", 59, "void", "Returns the hardware keypad type."},
    {"get_event", 261, "struct s_ns_event *event", "Gets next system event."},
    {"send_key_event", 262,
     "struct s_ns_event *event, unsigned short key, BOOL, BOOL",
     "Sends a key event to OS."},
    {"send_click_event", 263,
     "struct s_ns_event *event, unsigned short, BOOL, BOOL",
     "Sends a click event to OS."},
    {"send_pad_event", 264,
     "struct s_ns_event *event, unsigned short, BOOL, BOOL",
     "Sends a touchpad event to OS."},
    {"getcwd", 265, "char *buf, size_t size",
     "Gets current working directory."},
    {"read_nand", 336,
     "void *dest, int size, int offset, int u, int max, void *cb",
     "Reads raw NAND memory."},
    {"write_nand", 337, "void *src, int size, unsigned int offset",
     "Writes raw NAND memory."},
    {"nand_erase_range", 338, "int start, int end",
     "Erases a block of NAND memory."},

    /* Lua C API */
    {"luaL_register", 98,
     "lua_State *L, const char *libname, const luaL_Reg *l",
     "Registers C functions to Lua."},
    {"luaL_checklstring", 99, "lua_State *L, int arg, size_t *l",
     "Checks for string argument."},
    {"luaL_error", 100, "lua_State *L, const char *fmt, ...",
     "Raises Lua error."},
    {"luaI_openlib", 101,
     "lua_State *L, const char *libname, const luaL_Reg *l, int nup",
     "Opens a Lua library."},
    {"luaL_getmetafield", 102, "lua_State *L, int obj, const char *e",
     "Pushes metafield onto stack."},
    {"luaL_callmeta", 103, "lua_State *L, int obj, const char *e",
     "Calls a metamethod."},
    {"luaL_typerror", 104, "lua_State *L, int arg, const char *tname",
     "Generates a type error."},
    {"luaL_argerror", 105, "lua_State *L, int arg, const char *extramsg",
     "Generates an arg error."},
    {"luaL_optlstring", 106,
     "lua_State *L, int arg, const char *def, size_t *l",
     "Gets optional string arg."},
    {"luaL_checknumber", 107, "lua_State *L, int arg",
     "Checks for number arg."},
    {"luaL_optnumber", 108, "lua_State *L, int arg, lua_Number def",
     "Gets optional number arg."},
    {"luaL_checkinteger", 109, "lua_State *L, int arg",
     "Checks for integer arg."},
    {"luaL_optinteger", 110, "lua_State *L, int arg, lua_Integer def",
     "Gets optional integer arg."},
    {"luaL_checkstack", 111, "lua_State *L, int sz, const char *msg",
     "Grows stack size safely."},
    {"luaL_checktype", 112, "lua_State *L, int arg, int t",
     "Checks type of argument."},
    {"luaL_checkany", 113, "lua_State *L, int arg",
     "Checks if argument exists."},
    {"luaL_newmetatable", 114, "lua_State *L, const char *tname",
     "Creates a metatable."},
    {"luaL_checkudata", 115, "lua_State *L, int arg, const char *tname",
     "Checks userdata type."},
    {"luaL_where", 116, "lua_State *L, int lvl",
     "Pushes code location string."},
    {"luaL_checkoption", 117,
     "lua_State *L, int arg, const char *def, const char *const lst[]",
     "Checks string against list."},
    {"luaL_ref", 118, "lua_State *L, int t", "Creates a reference in table."},
    {"luaL_unref", 119, "lua_State *L, int t, int ref",
     "Releases a reference."},
    {"luaL_loadfile", 120, "lua_State *L, const char *filename",
     "Loads a Lua file as chunk."},
    {"luaL_loadbuffer", 121,
     "lua_State *L, const char *buff, size_t sz, const char *name",
     "Loads buffer as chunk."},
    {"luaL_loadstring", 122, "lua_State *L, const char *s",
     "Loads string as chunk."},
    {"luaL_newstate", 123, "void", "Creates new Lua state."},
    {"luaL_gsub", 124,
     "lua_State *L, const char *s, const char *p, const char *r",
     "String substitution."},
    {"luaL_findtable", 125,
     "lua_State *L, int idx, const char *fname, int szhint",
     "Finds/creates table."},
    {"luaL_buffinit", 126, "lua_State *L, luaL_Buffer *B",
     "Initializes string buffer."},
    {"luaL_prepbuffer", 127, "luaL_Buffer *B", "Returns buffer memory ptr."},
    {"luaL_addlstring", 128, "luaL_Buffer *B, const char *s, size_t l",
     "Adds string to buffer."},
    {"luaL_addstring", 129, "luaL_Buffer *B, const char *s",
     "Adds C string to buffer."},
    {"luaL_addvalue", 130, "luaL_Buffer *B", "Adds stack top to buffer."},
    {"luaL_pushresult", 131, "luaL_Buffer *B", "Pushes buffer onto stack."},
    {"lua_newstate", 132, "lua_Alloc f, void *ud",
     "Creates state with custom allocator."},
    {"lua_close", 133, "lua_State *L", "Destroys all Lua objects."},
    {"lua_newthread", 134, "lua_State *L", "Creates a new thread/coroutine."},
    {"lua_atpanic", 135, "lua_State *L, lua_CFunction panicf",
     "Sets panic function."},
    {"lua_gettop", 136, "lua_State *L", "Gets top index of stack."},
    {"lua_settop", 137, "lua_State *L, int idx", "Sets top index of stack."},
    {"lua_pushvalue", 138, "lua_State *L, int idx", "Copies value to top."},
    {"lua_remove", 139, "lua_State *L, int idx", "Removes element at index."},
    {"lua_insert", 140, "lua_State *L, int idx", "Moves top element to index."},
    {"lua_replace", 141, "lua_State *L, int idx", "Replaces element at index."},
    {"lua_checkstack", 142, "lua_State *L, int extra", "Ensures stack size."},
    {"lua_xmove", 143, "lua_State *from, lua_State *to, int n",
     "Moves values between threads."},
    {"lua_isnumber", 144, "lua_State *L, int idx",
     "Checks if value is number."},
    {"lua_isstring", 145, "lua_State *L, int idx",
     "Checks if value is string."},
    {"lua_iscfunction", 146, "lua_State *L, int idx",
     "Checks if value is C function."},
    {"lua_isuserdata", 147, "lua_State *L, int idx",
     "Checks if value is userdata."},
    {"lua_type", 148, "lua_State *L, int idx", "Returns type of value."},
    {"lua_typename", 149, "lua_State *L, int tp", "Returns type name."},
    {"lua_equal", 150, "lua_State *L, int idx1, int idx2",
     "Checks if values are equal."},
    {"lua_rawequal", 151, "lua_State *L, int idx1, int idx2",
     "Checks if values are raw equal."},
    {"lua_lessthan", 152, "lua_State *L, int idx1, int idx2",
     "Checks if value 1 < value 2."},
    {"lua_tonumber", 153, "lua_State *L, int idx", "Converts value to number."},
    {"lua_tointeger", 154, "lua_State *L, int idx",
     "Converts value to integer."},
    {"lua_toboolean", 155, "lua_State *L, int idx",
     "Converts value to boolean."},
    {"lua_tolstring", 156, "lua_State *L, int idx, size_t *len",
     "Converts value to string."},
    {"lua_objlen", 157, "lua_State *L, int idx", "Returns length of object."},
    {"lua_tocfunction", 158, "lua_State *L, int idx",
     "Converts value to C function."},
    {"lua_touserdata", 159, "lua_State *L, int idx",
     "Converts value to userdata."},
    {"lua_tothread", 160, "lua_State *L, int idx", "Converts value to thread."},
    {"lua_topointer", 161, "lua_State *L, int idx",
     "Converts value to void pointer."},
    {"lua_pushnil", 162, "lua_State *L", "Pushes nil."},
    {"lua_pushnumber", 163, "lua_State *L, lua_Number n", "Pushes number."},
    {"lua_pushinteger", 164, "lua_State *L, lua_Integer n", "Pushes integer."},
    {"lua_pushlstring", 165, "lua_State *L, const char *s, size_t len",
     "Pushes string by length."},
    {"lua_pushstring", 166, "lua_State *L, const char *s", "Pushes C string."},
    {"lua_pushfstring", 168, "lua_State *L, const char *fmt, ...",
     "Pushes formatted string."},
    {"lua_pushcclosure", 169, "lua_State *L, lua_CFunction fn, int n",
     "Pushes C closure."},
    {"lua_pushboolean", 170, "lua_State *L, int b", "Pushes boolean."},
    {"lua_gettable", 171, "lua_State *L, int idx", "Pushes t[k]."},
    {"lua_getfield", 172, "lua_State *L, int idx, const char *k",
     "Pushes t[k] string key."},
    {"lua_rawget", 173, "lua_State *L, int idx", "Pushes t[k] raw."},
    {"lua_rawgeti", 174, "lua_State *L, int idx, int n",
     "Pushes t[n] raw integer."},
    {"lua_createtable", 175, "lua_State *L, int narr, int nrec",
     "Creates preallocated table."},
    {"lua_newuserdata", 176, "lua_State *L, size_t size",
     "Allocates userdata."},
    {"lua_getmetatable", 177, "lua_State *L, int idx",
     "Pushes metatable of value."},
    {"lua_getfenv", 178, "lua_State *L, int idx", "Pushes environment table."},
    {"lua_settable", 179, "lua_State *L, int idx", "Sets t[k] = v."},
    {"lua_setfield", 180, "lua_State *L, int idx, const char *k",
     "Sets t[k] = v string key."},
    {"lua_rawset", 181, "lua_State *L, int idx", "Sets t[k] = v raw."},
    {"lua_rawseti", 182, "lua_State *L, int idx, int n",
     "Sets t[n] = v raw integer."},
    {"lua_setmetatable", 183, "lua_State *L, int idx",
     "Sets metatable of value."},
    {"lua_setfenv", 184, "lua_State *L, int idx", "Sets environment table."},
    {"lua_call", 185, "lua_State *L, int nargs, int nresults",
     "Calls a function."},
    {"lua_pcall", 186, "lua_State *L, int nargs, int nresults, int errfunc",
     "Calls function safely."},
    {"lua_cpcall", 187, "lua_State *L, lua_CFunction func, void *ud",
     "Calls C function safely."},
    {"lua_load", 188,
     "lua_State *L, lua_Reader reader, void *dt, const char *cn",
     "Loads Lua chunk."},
    {"lua_dump", 189, "lua_State *L, lua_Writer writer, void *data",
     "Dumps chunk as bytecode."},
    {"lua_yield", 190, "lua_State *L, int nresults", "Yields coroutine."},
    {"lua_resume", 191, "lua_State *L, int narg", "Resumes coroutine."},
    {"lua_status", 192, "lua_State *L", "Returns thread status."},
    {"lua_gc", 193, "lua_State *L, int what, int data",
     "Controls garbage collector."},
    {"lua_error", 194, "lua_State *L", "Generates a Lua error."},
    {"lua_next", 195, "lua_State *L, int idx",
     "Pops key, pushes next key-value."},
    {"lua_concat", 196, "lua_State *L, int n",
     "Concatenates n values on stack."},
    {"lua_getstack", 197, "lua_State *L, int level, lua_Debug *ar",
     "Gets info about call stack."},

    /* UTF-16 String Extension API */
    {"ascii2utf16", 13, "void *buf, const char *str, int max_size",
     "Converts ASCII to UTF16."},
    {"utf162ascii", 201, "char *buf, const uint16_t *str, int max_size",
     "Converts UTF16 to ASCII."},
    {"utf16_strlen", 202, "const uint16_t *str",
     "Returns the length of a UTF16 string."},
    {"string_new", 209, "void", "Returns a new empty String structure."},
    {"string_free", 210, "String str", "Frees the String structure."},
    {"string_to_ascii", 211, "String str",
     "Returns String converted to ASCII."},
    {"string_lower", 212, "String str", "Lowers all characters in String."},
    {"string_charAt", 213, "String str, int pos",
     "Returns the character at pos."},
    {"string_concat_utf16", 214, "String str, const char *utf16",
     "Concatenates a utf16 string."},
    {"string_set_ascii", 215, "String str, const char *ascii",
     "Erases content with an ASCII string."},
    {"string_set_utf16", 216, "String str, const char *utf16",
     "Erases content with a utf16 string."},
    {"string_indexOf_utf16", 217, "String str, int start, const char *pattern",
     "Returns the index of a pattern."},
    {"string_last_indexOf_utf16", 218,
     "String str, int start, const char *pattern",
     "Returns last index of pattern."},
    {"string_compareTo_utf16", 219, "String str, const char *pattern",
     "Compares String to utf16 string."},
    {"string_substring", 220, "String dst, String src, int start, int end",
     "Extracts a substring."},
    {"string_erase", 221, "String str, int n", "Erases first n characters."},
    {"string_truncate", 222, "String str, int n",
     "Truncates String to n characters."},
    {"string_substring_utf16", 223, "String str, const char *pat, int *ptr",
     "Returns string up to pattern."},
    {"string_insert_replace_utf16", 224,
     "String str, const char *pat, int start, int end",
     "Replaces a substring."},
    {"string_insert_utf16", 225, "String str, const char *pat, int pos",
     "Inserts utf16 at pos."},
    {"string_sprintf_utf16", 226, "String str, const char *fmt, ...",
     "Formatted print to UTF16 String."},

    /* Graphic Context (GC) API */
    {"gui_gc_global_GC_ptr", 298, "void", "Pointer to OS allocated Gc."},
    {"gui_gc_free", 299, "Gc gc", "Frees the given Graphic Context."},
    {"gui_gc_copy", 300, "Gc gc, int w, int h",
     "Allocates a new Gc copying parameters (not buffer)."},
    {"gui_gc_begin", 301, "Gc gc", "Initializes graphic port before drawing."},
    {"gui_gc_finish", 302, "Gc gc", "Cleans up graphic port parameters."},
    {"gui_gc_clipRect", 303, "Gc gc, int x, int y, int w, int h, int op",
     "Constrains drawing to region."},
    {"gui_gc_setColorRGB", 304, "Gc gc, int r, int g, int b",
     "Changes the pen color (RGB)."},
    {"gui_gc_setColor", 305, "Gc gc, int color",
     "Changes pen color (0xRRGGBB)."},
    {"gui_gc_setAlpha", 306, "Gc gc, int alpha", "Sets pen alpha mode."},
    {"gui_gc_setFont", 307, "Gc gc, gui_gc_Font font",
     "Changes the active font."},
    {"gui_gc_getFont", 308, "Gc gc", "Returns the current font."},
    {"gui_gc_setPen", 309, "Gc gc, gui_gc_PenSize size, gui_gc_PenMode mode",
     "Changes the pen size and mode."},
    {"gui_gc_setRegion", 310,
     "Gc gc, int xs, int ys, int ws, int hs, int x, int y, int w, int h",
     "Sets region viewport."},
    {"gui_gc_drawArc", 311,
     "Gc gc, int x, int y, int w, int h, int start, int end", "Draws an arc."},
    {"gui_gc_drawIcon", 312, "Gc gc, int res, int icon, int x, int y",
     "Draws OS predefined icon."},
    {"gui_gc_drawSprite", 313, "Gc gc, gui_gc_Sprite *spr, int x, int y",
     "Draws a sprite array."},
    {"gui_gc_drawLine", 314, "Gc gc, int x1, int y1, int x2, int y2",
     "Draws a line."},
    {"gui_gc_drawRect", 315, "Gc gc, int x, int y, int w, int h",
     "Draws an empty rectangle."},
    {"gui_gc_drawString", 316,
     "Gc gc, char *utf16, int x, int y, gui_gc_StringMode flags",
     "Draws a UTF16 string."},
    {"gui_gc_drawPoly", 317, "Gc gc, unsigned int *points, unsigned int count",
     "Draws a polygon shape."},
    {"gui_gc_fillArc", 318,
     "Gc gc, int x, int y, int w, int h, int start, int end", "Fills an arc."},
    {"gui_gc_fillPoly", 319, "Gc gc, unsigned int *points, unsigned int count",
     "Fills a polygon shape."},
    {"gui_gc_fillRect", 320, "Gc gc, int x, int y, int w, int h",
     "Fills a rectangle."},
    {"gui_gc_fillGradient", 321,
     "Gc gc, int x, int y1, int w, int y2, int c1, int c2, int vert",
     "Fills a gradient."},
    {"gui_gc_drawImage", 322, "Gc gc, char *TI_Image, int x, int y",
     "Draws an image in TI.Image format."},
    {"gui_gc_getStringWidth", 323,
     "Gc gc, gui_gc_Font font, char *utf16, int start, int len",
     "Gets string pixel width."},
    {"gui_gc_getCharWidth", 324, "Gc gc, gui_gc_Font font, short utf16_char",
     "Gets width of character."},
    {"gui_gc_getStringSmallHeight", 325,
     "Gc gc, gui_gc_Font font, char *utf16, int start, int len",
     "Gets small height of string."},
    {"gui_gc_getCharHeight", 326, "Gc gc, gui_gc_Font font, short utf16_char",
     "Gets the height of a character."},
    {"gui_gc_getStringHeight", 327,
     "Gc gc, gui_gc_Font font, char *utf16, int start, int len",
     "Gets full height of string."},
    {"gui_gc_getFontHeight", 328, "Gc gc, gui_gc_Font font",
     "Gets max height of font."},
    {"gui_gc_getIconSize", 329, "Gc gc, int res, int icon, int *w, int *h",
     "Gets dimensions of OS icon."},
    {"gui_gc_blit_gc", 330,
     "Gc src, int xs, int ys, int ws, int hs, Gc dst, int xd, int yd, int wd, "
     "int hd",
     "Blits and stretches from one Gc to another."},
    {"gui_gc_blit_buffer", 331,
     "Gc gc, char *buffer, int xb, int yb, int wb, int hb",
     "Blits from a raw buffer to a Gc."},

    /* Miscellaneous OS Services & Menus */
    {"refresh_homescr", 198, "void", "Refreshes the TI-Nspire homescreen."},
    {"refresh_docbrowser", 199, "int p1", "Refreshes the Document Browser."},
    {"_show_1NumericInput", 203,
     "int p1, const char *title, const char *sub, const char *lbl, int *val, "
     "...",
     "Shows a 1-numeric input dialog."},
    {"_show_2NumericInput", 204,
     "int p1, const char *title, const char *sub, const char *lbl1, int *val1, "
     "...",
     "Shows a 2-numeric input dialog."},
    {"_show_msgUserInput", 205,
     "int p1, String *str, const char *title, const char *sub",
     "Shows a text input dialog."},
    {"calc_cmd", 339,
     "void *p1, void *p2, const uint16_t *expr, void *p4, void *p5",
     "Evaluates a math expression."},
    {"get_res_string", 340, "int res, int strid",
     "Gets OS translated resource string."},
    {"disp_str", 341, "const char *str, int *x, int y",
     "Displays a basic string to LCD."},
    {"TI_MS_MathExprToStr", 342, "void *p1, void *p2, uint16_t **str",
     "Converts math expression object to string."},
    {"get_documents_dir", 297, "void", "Returns path to /documents."},

    /* USB Host Driver API (usbd_) */
    {"usbd_open_pipe", 227,
     "usbd_interface_handle ih, uint8_t a, uint8_t e, usbd_pipe_handle *p",
     "Opens USB pipe."},
    {"usbd_close_pipe", 228, "usbd_pipe_handle p", "Closes USB pipe."},
    {"usbd_transfer", 229, "usbd_xfer_handle xfer", "Initiates USB transfer."},
    {"usbd_alloc_xfer", 230, "usbd_device_handle dev",
     "Allocates USB transfer struct."},
    {"usbd_free_xfer", 231, "usbd_xfer_handle xfer",
     "Frees USB transfer struct."},
    {"usbd_setup_xfer", 232,
     "usbd_xfer_handle xfer, usbd_pipe_handle p, usbd_private_handle priv, ...",
     "Setups standard transfer."},
    {"usbd_setup_isoc_xfer", 233,
     "usbd_xfer_handle xfer, usbd_pipe_handle p, usbd_private_handle priv, ...",
     "Setups isochronous transfer."},
    {"usbd_get_xfer_status", 234,
     "usbd_xfer_handle xfer, usbd_private_handle *p, void **b, uint32_t *len, "
     "usbd_status *s",
     "Gets transfer status."},
    {"usbd_interface2endpoint_descriptor", 235,
     "usbd_interface_handle ih, uint8_t e", "Gets endpoint desc."},
    {"usbd_abort_pipe", 236, "usbd_pipe_handle p",
     "Aborts pending transfers on pipe."},
    {"usbd_clear_endpoint_stall", 237, "usbd_pipe_handle p",
     "Clears stall condition on endpoint."},
    {"usbd_endpoint_count", 238, "usbd_interface_handle ih, uint8_t *c",
     "Gets number of endpoints."},
    {"usbd_interface_count", 239, "usbd_device_handle dev, uint8_t *c",
     "Gets number of interfaces."},
    {"usbd_interface2device_handle", 240,
     "usbd_interface_handle ih, usbd_device_handle *dev",
     "Gets device from interface."},
    {"usbd_device2interface_handle", 241,
     "usbd_device_handle dev, uint8_t iface, usbd_interface_handle *ih",
     "Gets interface from device."},
    {"usbd_pipe2device_handle", 242, "usbd_pipe_handle p",
     "Gets device from pipe."},
    {"usbd_sync_transfer", 243, "usbd_xfer_handle xfer",
     "Executes synchronous transfer."},
    {"usbd_open_pipe_intr", 244,
     "usbd_interface_handle ih, uint8_t a, uint8_t e, usbd_pipe_handle *p, ...",
     "Opens interrupt pipe."},
    {"usbd_do_request", 245,
     "usbd_device_handle dev, usb_device_request_t *req, void *data",
     "Executes control request."},
    {"usbd_do_request_flags", 246,
     "usbd_device_handle dev, usb_device_request_t *req, void *data, uint16_t "
     "f, int *act",
     "Executes control request with flags."},
    {"usbd_do_request_flags_pipe", 247,
     "usbd_device_handle dev, usbd_pipe_handle p, usb_device_request_t *req, "
     "...",
     "Executes request on specific pipe."},
    {"usbd_get_interface_descriptor", 248, "usbd_interface_handle ih",
     "Gets interface descriptor."},
    {"usbd_get_config_descriptor", 249, "usbd_device_handle dev",
     "Gets config descriptor."},
    {"usbd_get_device_descriptor", 250, "usbd_device_handle dev",
     "Gets device descriptor."},
    {"usbd_set_interface", 251, "usbd_interface_handle ih, int alt",
     "Sets interface alternate setting."},
    {"usbd_get_interface", 252, "usbd_interface_handle ih, uint8_t *alt",
     "Gets interface alternate setting."},
    {"usbd_find_idesc", 253, "usb_config_descriptor_t *cd, int i, int a",
     "Finds interface descriptor inside config."},
    {"usbd_errstr", 254, "usbd_status err", "Returns USB error string."},
    {"usbd_devinfo", 255, "usbd_device_handle dev, int b, char *str",
     "Gets device info string."},
    {"usbd_get_quirks", 256, "usbd_device_handle dev",
     "Gets USB device quirks."},
    {"usbd_get_endpoint_descriptor", 257, "usbd_interface_handle ih, uint8_t e",
     "Gets endpoint descriptor by index."},
    {"usb_register_driver", 258,
     "int p1, int(*p2[])(device_t), const char* p3, int p4, unsigned int p5",
     "Registers USB class driver."},
    {"device_get_softc", 259, "device_t dev", "Gets softc of device."},
    {"device_get_ivars", 260, "device_t dev", "Gets ivars of device."},

    /* NavNet Protocol API */
    {"TI_NN_SendKeyPress", 267, "void", "Sends key press via NavNet."},
    {"TI_NN_IsNodeResponsive", 268, "void", "Checks if remote node responds."},
    {"TI_NN_NodeEnumDone", 269, "nn_oh_t oh", "Terminates node enumeration."},
    {"TI_NN_NodeEnumNext", 270, "nn_oh_t oh, nn_nh_t *nh",
     "Gets next node in enumeration."},
    {"TI_NN_GetConnMaxPktSize", 271, "nn_ch_t ch",
     "Gets max packet size for connection."},
    {"TI_NN_Read", 272,
     "nn_ch_t ch, uint32_t timeout_ms, void *buf, uint32_t buf_size, uint32_t "
     "*recv_size",
     "Reads packet from NavNet."},
    {"TI_NN_Write", 273, "nn_ch_t ch, void *buf, uint32_t data_size",
     "Writes packet to NavNet."},
    {"TI_NN_StartService", 274,
     "uint32_t id, void *data, void(*cb)(nn_ch_t,void*)",
     "Exposes a NavNet service."},
    {"TI_NN_StopService", 275, "uint32_t service_id",
     "Stops exposing a service."},
    {"TI_NN_Connect", 276, "nn_nh_t nh, uint32_t service_id, nn_ch_t *ch",
     "Connects to a remote NavNet service."},
    {"TI_NN_Disconnect", 277, "nn_ch_t ch", "Disconnects from remote service."},
    {"TI_NN_NodeEnumInit", 278, "nn_oh_t oh",
     "Initiates NavNet node enumeration."},
    {"TI_NN_UnregisterNotifyCallback", 279, "void",
     "Unregisters NavNet event callback."},
    {"TI_NN_RegisterNotifyCallback", 280, "uint32_t flags, void (*cb)(void)",
     "Registers for NavNet events."},
    {"TI_NN_InstallOS", 281, "void", "Initiates remote OS install."},
    {"TI_NN_GetNodeInfo", 282, "void", "Gets information about remote node."},
    {"TI_NN_DestroyOperationHandle", 283, "nn_oh_t oh",
     "Destroys NavNet operation handle."},
    {"TI_NN_CreateOperationHandle", 284, "void",
     "Creates NavNet operation handle."},
    {"TI_NN_GetNodeScreen", 285, "void", "Captures remote node screen."},
    {"TI_NN_CopyFile", 286, "void", "Copies remote file."},
    {"TI_NN_Rename", 287, "void", "Renames remote file/folder."},
    {"TI_NN_RmDir", 288, "void", "Removes remote directory."},
    {"TI_NN_MkDir", 289, "void", "Creates remote directory."},
    {"TI_NN_DeleteFile", 290, "void", "Deletes remote file."},
    {"TI_NN_GetFileAttributes", 291, "void", "Gets remote file attributes."},
    {"TI_NN_PutFile", 292,
     "nn_nh_t nh, nn_oh_t oh, const char *local, const char *remote",
     "Transfers file via NavNet."},
    {"TI_NN_DirEnumDone", 293, "void",
     "Terminates remote directory enumeration."},
    {"TI_NN_DirEnumNext", 294, "void", "Gets next remote directory entry."},
    {"TI_NN_DirEnumInit", 295, "void",
     "Initiates remote directory enumeration."},
    {"TI_NN_GetFile", 296, "void", "Receives file via NavNet."},

    /* Ndless OS Extensions (Requires 0x200000 bitmask) */
    {"nl_osvalue", 0x200000, "const int values[], unsigned size",
     "Returns OS-dependent array value."},
    {"nl_relocdatab", 0x200001, "void",
     "Returns base address of .data relocations."},
    {"nl_hwtype", 0x200002, "void",
     "Returns the hardware type ID (0=Clickpad, 1=Touchpad, etc)."},
    {"nl_isstartup", 0x200003, "void",
     "Returns TRUE if program is running at OS startup."},
    {"nl_lua_getstate", 0x200004, "void",
     "Returns global Lua state of current document."},
    {"nl_set_resident", 0x200005, "void",
     "Marks program to not free memory on exit."},
    {"nl_ndless_rev", 0x200006, "void",
     "Returns the current Ndless revision number."},
    {"nl_no_scr_redraw", 0x200007, "void",
     "Prevents screen restore on program exit."},
    {"nl_loaded_by_3rd_party_loader", 0x200008, "void",
     "Returns TRUE if loaded by 3rd party loader."},
    {"nl_hwsubtype", 0x200009, "void",
     "Returns hardware sub-type (CX/CX-II vs Older)."},
    {"nl_exec", 0x20000A, "const char *prgm_path, int argsn, char *args[]",
     "Executes another .tns program."},
    {"nl_osid", 0x20000B, "void", "Returns exact OS version identifier."},
    {"_nl_hassyscall", 0x20000C, "int syscall_num",
     "Checks if a specific syscall is available."},
    {"nl_lcd_blit", 0x20000D, "void",
     "Blits Ndless internal FB to hardware LCD."},
    {"nl_lcd_type", 0x20000E, "void", "Returns the physical LCD panel type."},
    {"nl_lcd_init", 0x20000F, "void",
     "Re-initializes hardware LCD parameters."},

    /* Emulator Integration (Requires 0x400000 bitmask) */
    {"NDLSEMU_DEBUG_ALLOC", 0x400000, "void *ptr, size_t size",
     "Notifies emulator of memory allocation."},
    {"NDLSEMU_DEBUG_FREE", 0x400001, "void *ptr",
     "Notifies emulator of memory free."}};
#define NSYSCALLS ((int)(sizeof(db_syscalls) / sizeof(db_syscalls[0])))
const int g_nsyscalls = NSYSCALLS;

const char *get_syscall_name(long num) {
  for (int i = 0; i < NSYSCALLS; i++) {
    if (db_syscalls[i].num == num)
      return db_syscalls[i].name;
  }
  return NULL;
}

/* Look up a mnemonic name (any case) in the full database, accepting an
   optional 'S' suffix and a condition code at any valid position (both
   pre-UAL and UAL suffix orders, matching what nasm assembles).
   Returns the MnemInfo, or NULL if not found. */
static const MnemInfo *lookup_exact(const char *word, int wlen) {
  for (int c = 0; c < NCATS; c++) {
    for (int m = 0; m < g_cats[c].count; m++) {
      const MnemInfo *mi = &g_cats[c].mnems[m];
      int nl = (int)strlen(mi->name);
      if (nl == wlen && strncaseeq(mi->name, word, wlen))
        return mi;
    }
  }
  return NULL;
}

const MnemInfo *cheatsheet_lookup(const char *word, int wlen) {
  catalog_init_cats();

  if (wlen <= 0 || wlen >= 16)
    return NULL;

  const MnemInfo *mi = lookup_exact(word, wlen);
  if (mi)
    return mi;

  /* Two base variants: as-is, and with a trailing S stripped. */
  for (int strip_s = 0; strip_s < 2; strip_s++) {
    char base[16];
    int blen = wlen;
    memcpy(base, word, wlen);
    base[wlen] = '\0';

    if (strip_s) {
      if (blen < 2 || (base[blen - 1] != 's' && base[blen - 1] != 'S'))
        continue;
      base[--blen] = '\0';
      mi = lookup_exact(base, blen);
      if (mi)
        return mi;
    }

    /* Remove a condition code at any position. */
    for (int p = 1; p + 2 <= blen; p++) {
      char cc[3] = {base[p], base[p + 1], '\0'};
      if (!is_condcode(cc))
        continue;
      char cand[16];
      memcpy(cand, base, p);
      memcpy(cand + p, base + p + 2, blen - p - 2);
      int clen = blen - 2;
      cand[clen] = '\0';
      mi = lookup_exact(cand, clen);
      if (mi)
        return mi;
      /* cond before a trailing S (pre-UAL, e.g. ADDEQS) */
      if (clen >= 2 && (cand[clen - 1] == 's' || cand[clen - 1] == 'S')) {
        mi = lookup_exact(cand, clen - 1);
        if (mi)
          return mi;
      }
    }
  }
  return NULL;
}
